### ISSUE TITLE
Ανάρτηση του Project-Plan-v.0.2

### ISSUE THREAD

**Issue by manderlyFries** [DimitrisDemos/projectSoftTech#21]
Μαζί με το δεύτερο παραδοτέο να αναρτήσουμε και το v0.2 του Project-Plan, στο οποίο έγιναν μικροτροποποιήσεις στα Βασικά Εργαλεία και προστέθηκε και το ανάλογο Changelog.

**Comment by Mamel11** [comment]
Δεδομένου ότι πρόκειται για μικροτροποποιήσεις μήπως περιτευέι το να το ανεβάσουμε, ο΄τως ή άλλως θα χρειαστεί να καταθέσουμε v0.2 μόλις πάρουμε το feedbask από 'βδομάδα;
