### ISSUE TITLE
ΔΙΟΡΘΩΣΗ 1ου ΠΑΡΑΔΟΤΕΟΥ ΣΤΗ ΒΑΣΗ ΤΟΥ FEEDBACK ΠΟΥ ΛΑΒΑΜΕ

### ISSUE THREAD

**Issue by manderlyFries** [DimitrisDemos/projectSoftTech#22]

**Comment by manderlyFries** [comment]
1.Project Description εχει πολλους τεχνικους ορους, μη φυσική γλώσσα
2.Mockups  "δεν είναι καλά"
3.Risk Assessment είναι πολύ γενικα
4.Αλλαγή στο PERT που έχει γίνει καποιο λάθος

**Comment by Mamel11** [comment]
Eχουν ανέβει αρκετά project description πλεον. Ποιο θεωρούμε τελικό;
