### ISSUE TITLE
ΔΙΟΡΘΩΣΗ ΤΟΥ 2ου ΠΑΡΑΔΟΤΕΟΥ ΣΤΗ ΒΑΣΗ ΤΟΥ FEEDBACK

### ISSUE THREAD

**Issue by manderlyFries** [DimitrisDemos/projectSoftTech#23]

**Comment by manderlyFries** [comment]
1.Πρέπει να γινουν πιο σύνθετα τα use cases. Με περισσότερες λεπτομέριες αλληλεπίδρασης χρήστη και συστήματος.
2.Δε πρεπει στα use cases να υπάρχουν στοιχεία γραφικών (κουμπιά πχ)
3.Το check in πρέπει να δούμε επίσης
4.Η κάμερα ίσως πρέπει να γίνει actor.

**Comment by Mamel11** [comment]
Κοιτάζοντα τα use cases στον φάκελο current δεν βλέπω κάτι άλλο να εκκρεμεί. Κάνω λάθος;
