### ISSUE TITLE
Βάζετε λάθος το ΑΜ μου

### ISSUE THREAD

**Issue by Mamel11** [DimitrisDemos/projectSoftTech#32]
Είναι 1054286
Θα τα φτιάξω πριν παραδώσουμε αφού ανεβαίνουν από τον δικό μου λογαριασμό απλά το λέω.

**Comment by manderlyFries** [comment]
1054286 ειναι το σωστο

**Comment by manderlyFries** [comment]
στα project-description και risk assessment και usecases διορθωθηκε!
