### ISSUE TITLE
ΠΑΡΑΔΟΤΕΟ 3: ROBUSTNESS - CHECK OUT + SEARCH PARKING + SEARCH DESTINATION

### ISSUE THREAD

**Issue by manderlyFries** [DimitrisDemos/projectSoftTech#40]

**Comment by DimitrisDemos** [comment]
![Image](https://user-images.githubusercontent.com/106690813/234385749-b301b113-f861-4fcd-90da-89051ca1dc65.png)
![Image](https://user-images.githubusercontent.com/106690813/234385747-35d63e99-e53f-4398-8c50-940bc34fad77.png)
![Image](https://user-images.githubusercontent.com/106690813/234385748-d57660b7-1a47-4c0e-8676-6f6a1e52e34a.png)
